name: 'CI/CD pipeline'

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  run_test:
    runs-on: ubuntu-latest 
    steps: 
      - 
        name: Checkout Repo 
        uses: actions/checkout@v2
      - 
        name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test 

  build_and_push_to_dockerhub:
    if: github.event.pull_request.merged == true  
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: andylim95/app:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
